routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/manager', function () {
    return redirect()->route('login');
});

Route::resource('/comentarios', 'CommentController')->only([
    'store'
]);

Route::group(['prefix' => 'manager', 'middleware' => 'auth'], function()
{
	Route::get('/articulos/favoritos', 'PostController@showFavorites')->name('articulos.showFavorites');

	Route::resources([
	    '/articulos' => 'PostController',
	    '/categorias' => 'CategoryController',
	    '/usuarios' => 'UserController',
	    '/redes' => 'SocialController'
	]);

	Route::post('/articulos/{articulo}/quitar', 'PostController@quit')->name('articulos.quit');

	Route::post('/categorias/{articulo}/{categoria}/quitar', 'CategoryController@quit')->name('categorias.quit');

	Route::resource('/roles', 'RoleController')->only([
	    'index', 'show'
	]);

	Route::get('/configuracion/cabecera', 'ConfigController@header')->name('configuracion.header');
});

Route::group(['middleware' => 'shareData'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/categoria/{slug}', 'HomeController@showPostByCategory')->name('category');
	Route::get('/autor/{username}', 'HomeController@showPostByUser')->name('autor');
	Route::get('/buscar', 'HomeController@search')->name('articulos.search');
	Route::get('/{slug}', 'HomeController@showPostBySlug')->name('post');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'firstname', 'lastname', 'website', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function categories()
    {
        return $this->hasMany('App\Category');
    }

    public function role()
    {
        return $this->belongsTo('App\Role');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\UserStoreRequest;
use App\Traits\ListRolesTrait;
use Illuminate\Support\Facades\Hash;
use App\Charts\UserContribution;

class UserController extends Controller
{
    use ListRolesTrait;

	public function __construct()
    {
        $this->middleware('checkRole:1');
    }

    public function index()
	{
    	$users = User::all();
    	return view('manager.users.all', ['users' => $users]);
	}

    public function show($id)
    {
        $user = User::findOrFail($id);
        $chartPost = new UserContribution;
        $chartPost->labels(['Otros', 'Tú']);
        $chartPost->dataset("DataSetPost", "doughnut", $chartPost->dataSetPostsByUser($user->id))->options([
            'backgroundColor' => ['#cecdcd', '#1d81a2'],
            'hoverBackgroundColor' => ['#a6a6a6', '#18667f']
        ]);

        $chartCategory = new UserContribution;
        $chartCategory->labels(['Otros', 'Tú']);
        $chartCategory->dataset("DataSetCategory", "doughnut", $chartCategory->dataSetCategoryByUser($user->id))->options([
            'backgroundColor' => ['#cecdcd', '#1d81a2'],
            'hoverBackgroundColor' => ['#a6a6a6', '#18667f']
        ]);

        
        return view('manager.users.show', compact('user', 'chartPost', 'chartCategory')); 
    }

	public function create()
	{
        $roles = $this->getAllRoles();
        return view('manager.users.create', compact('roles')); 
	}

	public function store(UserStoreRequest $request)
	{
	    $validated = $request->validated();
        $validated["password"] = Hash::make($validated["password"]);

    	User::create($validated);
    	return redirect()->route('usuarios.index');
	}

    public function edit($id)
    {
        $roles = $this->getAllRoles();
        $user = User::findOrFail($id);
        return view('manager.users.edit', compact('user', 'roles'));
    }

	public function update(UserUpdateRequest $request, $id) {
        $validated = $request->validated();

        if (isset($validated["password"]))
            $validated["password"] = Hash::make($request->password);
       
        $user = User::findOrFail($id);
        $user->update($validated);
        return redirect()->route('usuarios.index');
    }

	public function destroy($id)
    {
    	User::findOrFail($id)->delete();
    	return redirect()->route('usuarios.index');
    }
}

resources/views/manager/users/all.blade.php
@extends('layouts.manager')
@section('title', 'Listado de usuarios')
@section('description', 'Listado de usuarios en el backend')
@section('content')
	@include('manager.users.modalConfirmDelete')

		<div class="row">
		<div class="col-12">
			<div class="backend-card">
	            <div class="card-header">
	            	<h1><i class="far fa-folder-open"></i> Usuarios</h1>
	            </div>
	            <div class="card-body">
	                <div class="row">
	                    <div class="col-12">
							<a role="button" href="{{ route('usuarios.create') }}" class="btn btn-success pull-left"><i class="fas fa-plus"></i> Nuevo</a>
	                    </div>
	                </div>
	                <div class="row">
	                    <div class="col-12">
							<table id="dataTable" class="table table-hover table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
								<thead class="thead-dark"> 
									<tr> 
										<th>ID</th> 
										<th>Nombre</th>
										<th>Rol</th>
										<th>Artículos</th>
										<th>Categorias</th>
										<th>Creado</th> 
										<th>Acciones</th>
									</tr>
								</thead> 
								<tbody> 
									@foreach ($users as $user)
										<tr> 
											<td>{{$user->id}}</td>
											<td>{{$user->username}}</td>
											<td>
												<a href="{{route('roles.show', ['id' => $user->role])}}">{{$user->role->name}}</a> 	
											</td>
											<td>{{count($user->posts)}}</td>
											<td>{{count($user->categories)}}</td>
											<td>{{$user->created_at}}</td>
											<td>
												<div class="btn-group d-inline d-xl-none" role="group">
													<a href="{{route('usuarios.show', $user->id)}}" role="button" class="btn btn-success"><i class="far fa-eye"></i></a>
												 	<a href="{{route('usuarios.edit', $user->id)}}" role="button" class="btn btn-primary"><i class="far fa-edit"></i></a>	
												 	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{$user->id}}"><i class="far fa-trash-alt"></i></button>
												</div>

												<div class="d-none d-xl-block">
													<a href="{{route('usuarios.show', $user->id)}}" role="button" class="btn btn-outline-success"><i class="far fa-eye"></i> Ver</a>
				      								<a href="{{route('usuarios.edit', $user->id)}}" role="button" class="btn btn-outline-primary"><i class="far fa-edit"></i> Editar</a>
													<button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{$user->id}}"><i class="far fa-trash-alt"></i> Eliminar</button>
												</div>
											</td>
										</tr>
									@endforeach
								</tbody> 
							</table>
	                    </div>
	                </div>
	            </div>
	        </div>
    	</div>
	</div>
@endsection

resources/views/manager/users/create.blade.php
@extends('layouts.manager')
@section('title', 'Crear nuevo usuario')
@section('description', 'Creación de nuevos usuarios desde el backend')

@section('content')

    <form class="form-horizontal col-12" action="{{ route('usuarios.store') }}" method="POST">
        @csrf
        <div class="row mt-3">
            <div class=" col-12 text-right">
                <a href="{{route('usuarios.index')}}" role="button" class="btn btn-success"><i class="fas fa-arrow-left"></i> @lang('Volver')</a>
                <button type="submit" class="btn btn-primary">@lang('Crear')</button>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="backend-card">
                    <div class="card-header">
                        <div class="backend-card-title">@lang('Crear nuevo usuario')</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12">                            
                                <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ old('username') }}" required autocomplete="name" autofocus placeholder="@lang('Nombre de usuario') *">
                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>
                            
                            <div class="form-group col-12 input-group" id="showHidePassword">
                                <input type="password" class="form-control @error('password') is-invalid @enderror" required autocomplete="new-password" name="password" placeholder="@lang('Contraseña') *">
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-outline-secondary"><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                </div>
                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12 input-group" id="showHidePasswordRepeat">
                                <input id="password-confirm" type="password" class="form-control" placeholder="@lang('Repita contraseña') *" name="password_confirmation" required autocomplete="new-password">
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-outline-secondary"><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                </div>
                            </div>

                            <div class="form-group col-12">                            
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="@lang('Email') *" required autocomplete="email" value="{{ old('email') }}">
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">                            
                                <select class="form-control selectpicker" required name="role_id" title="Rol *">
                                    @foreach ($roles as $role)
                                        <option {{$role->id == old('role_id') ? "selected" : "" }} value="{{$role->id}}">{{$role->name}}</option>
                                    @endforeach
                                </select>
                                @error('role_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>    
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="backend-card">
                    <div class="card-header">
                        <div class="backend-card-title">@lang('Información personal')</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12">                            
                                <input type="text" class="form-control @error('username') is-invalid @enderror" name="firstname" placeholder="@lang('Nombre')" value="{{ old('firstname') }}">
                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">                            
                                <input type="text" class="form-control @error('lastname') is-invalid @enderror" name="lastname" placeholder="@lang('Apellidos')" value="{{ old('lastname') }}">
                                @error('lastname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">                            
                                <input type="url" class="form-control @error('website') is-invalid @enderror" name="website" placeholder="@lang('Web')" value="{{ old('website') }}">
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/manager/users/edit.blade.php
@extends('layouts.manager')
@section('title', 'Editar usuario')
@section('description', 'Edición de un usuario desde el backend')

@section('content')
    <form class="form-horizontal col-12" action="{{ route('usuarios.update', $user->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row mt-3">
            <div class="col-12 text-right">
                <a href="{{ url()->previous() }}" role="button" class="btn btn-success"><i class="fas fa-arrow-left"></i> Volver</a>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-6 col-12">
                <div class="backend-card">
                    <div class="card-header">
                        <div class="backend-card-title">Editar usuario</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12">                            
                                <label class="font-weight-bold">Nombre de usuario</label>
                                <input type="text" class="form-control @error('username') is-invalid @enderror" name="username" placeholder="Nombre de usuario" value="{{ old('username', $user->username) }}">
                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>
                            
                            <div class="form-group col-12" id="showHidePassword"> 
                                <label class="font-weight-bold">Contraseña</label>
                                <div class="input-group">
                                    <input type="password" class="form-control @error('password') is-invalid @enderror" autocomplete="new-password" name="password" placeholder="Contraseña *">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-outline-secondary"><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                    </div>
                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                     @enderror
                                </div>
                            </div>
                                
                            <div class="form-group col-12" id="showHidePasswordRepeat">   
                                <label class="font-weight-bold">Confirmar contraseña</label>
                                <div class="input-group">
                                    <input id="password-confirm" type="password" class="form-control" placeholder="Repita contraseña *" name="password_confirmation" autocomplete="new-password">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-outline-secondary"><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group col-12">
                                <label class="font-weight-bold">Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Email *" autocomplete="email" value="{{ old('email', $user->email) }}">
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">
                                <label class="font-weight-bold">Rol</label>
                                <select class="form-control selectpicker" name="role_id" title="Rol">
                                    @foreach ($roles as $role)
                                        @if ($user->role->id == $role->id)
                                            <option selected value="{{$role->id}}">{{$role->name}}</option>
                                        @else
                                            <option value="{{$role->id}}">{{$role->name}}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('role_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-6 col-12">
                <div class="backend-card">
                    <div class="card-header">
                        <div class="backend-card-title">Editar información personal</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12">
                                <label class="font-weight-bold">Nombre</label>
                                <input type="text" class="form-control @error('firstname') is-invalid @enderror" name="firstname" placeholder="Nombre" value="{{ old('firstname', $user->firstname) }}">
                                @error('firstname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">
                                <label class="font-weight-bold">Apellidos</label>
                                <input type="text" class="form-control @error('lastname') is-invalid @enderror" name="lastname" placeholder="Apellidos" value="{{ old('lastname', $user->lastname) }}">
                                @error('lastname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">
                                <label class="font-weight-bold">Dirección web</label>
                                <input type="url" class="form-control @error('website') is-invalid @enderror" name="website" placeholder="Web" value="{{ old('website', $user->website) }}">
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>
                        </div>
                    </div>
                </div>    
            </div>
        </div>
    </form>
@endsection

resources/views/manager/users/modalConfirmDelete.blade.php
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteUserModalConfirmaton" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class="col-3">
            <i class="fas fa-exclamation-triangle fa-4x text-danger"></i>
          </div>
          <div class="col-9">
            <div class="row">
              <div class="col-12">
                 <h5 class="font-weight-bold">Eliminar usuario</h5>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <p>Esta acción no se puede deshacer</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <form  id="deleteForm" action="{{route('usuarios.destroy', ['id' => 'placeHolderId'])}}" method="POST">
          @csrf
          @method('DELETE')
          <button type="button" class="btn" data-dismiss="modal">Cancelar</button>
          <button class="btn btn-danger" type="submit">Eliminar</button>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/manager/users/show.blade.php
@extends('layouts.manager')
@section('title', 'Ver usuario')
@section('description', 'Ver un usuario desde el backend')

@section('content')

    <div class="row mt-3">
        <div class="col-12 text-right">
            <a href="{{ url()->previous() }}" role="button" class="btn btn-success"><i class="fas fa-arrow-left"></i> Volver</a>
            <a href="{{route('usuarios.edit', $user->id)}}" role="button" class="btn btn-primary"><i class="far fa-edit"></i> Editar</a> 
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-xl-6">
            <div class="backend-card">
                <div class="card-header">
                    <div class="backend-card-title">Información del usuario</div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <label class="font-weight-bold">Nombre de usuario: </label><p class="d-inline"> {{$user->username}}</p>
                        </div>
                 
                        <div class="col-12">
                            <label class="font-weight-bold">Rol: </label><p class="d-inline"> <a href="{{route('roles.show', ['id' => $user->role])}}">{{$user->role->name}}</a></p>
                        </div>
                
                        <div class="col-12">
                            <label class="font-weight-bold">Creado en: </label><p class="d-inline"> {{$user->created_at}}</p>
                        </div>

                        <div class="col-12">
                             <label class="font-weight-bold">Email: </label><p class="d-inline"> {{$user->email}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-xl-6">
            <div class="backend-card">
                <div class="card-header">
                    <div class="backend-card-title">Información personal</div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <label class="font-weight-bold">Nombre: </label><p class="d-inline"> {{$user->firstname}}</p>
                        </div>

                        <div class="col-12">
                            <label class="font-weight-bold">Apellido: </label><p class="d-inline"> {{$user->lastname}}</p>
                        </div>
         
                        <div class="col-12">
                            <label class="font-weight-bold">Web: </label><p class="d-inline"> {{$user->website}}</p>
                        </div>
                    </div>
                </div>
            </div>    
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="backend-card">
                <div class="card-header">
                    <div class="backend-card-title">Contribución</div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-xl-6">
                            <div class="row">
                                <div class="col-12">
                                    <label class="font-weight-bold">Artículos creados</label>
                                </div>
                            </div> 
                            <div class="row">
                                <div class="col-12">
                                    {!! $chartPost->container() !!}
                                    {!! $chartPost->script() !!}
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-xl-6 mt-4 mt-xl-0">
                            <div class="row">
                                <div class="col-12">
                                    <label class="font-weight-bold">Categorías creadas</label>
                                </div>
                            </div> 
                            <div class="row">
                                <div class="col-12">
                                    {!! $chartCategory->container() !!}
                                    {!! $chartCategory->script() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection