routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/manager', function () {
    return redirect()->route('login');
});

Route::resource('/comentarios', 'CommentController')->only([
    'store'
]);

Route::group(['prefix' => 'manager', 'middleware' => 'auth'], function()
{
	Route::get('/articulos/favoritos', 'PostController@showFavorites')->name('articulos.showFavorites');

	Route::resources([
	    '/articulos' => 'PostController',
	    '/categorias' => 'CategoryController',
	    '/usuarios' => 'UserController',
	    '/redes' => 'SocialController'
	]);

	Route::post('/articulos/{articulo}/quitar', 'PostController@quit')->name('articulos.quit');

	Route::post('/categorias/{articulo}/{categoria}/quitar', 'CategoryController@quit')->name('categorias.quit');

	Route::resource('/roles', 'RoleController')->only([
	    'index', 'show'
	]);

	Route::get('/configuracion/cabecera', 'ConfigController@header')->name('configuracion.header');
});

Route::group(['middleware' => 'shareData'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/categoria/{slug}', 'HomeController@showPostByCategory')->name('category');
	Route::get('/autor/{username}', 'HomeController@showPostByUser')->name('autor');
	Route::get('/buscar', 'HomeController@search')->name('articulos.search');
	Route::get('/{slug}', 'HomeController@showPostBySlug')->name('post');
});

resources/views/includes/footer.blade.php
<div class="container mt-5 py-5">
	<div class="row">
		<div class="col-12">
			<div class="separator-footer">
				<h3>@lang('Sobre nosotros')</h3>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<div class="col-12">
			<p class="footer-text">
				{{$options['footer_text']->value}}
			</p>
		</div>
	</div>

	<div class="row footer-links mb-5">
		<div class="col-12 col-md-4 mb-3 mb-md-0">
			<a href="#">@lang('Sitemap')</a>
		</div>

		<div class="col-12 col-md-4 mb-3 mb-md-0 text-md-center text-left">
			<a href="#">@lang('Aviso legal y política de privacidad')</a>
		</div>

		<div class="col-12 col-md-4 text-md-right text-left">
			
			<a href="#">@lang('Política de cookies')</a>
		</div>	
	</div>

	<div class="row">
		<div class="col-12 text-white">
			{{$options['footer_webname']->value}} © {{date("Y")}}
		</div>
	</div>

</div>

<script src="{{ asset('js/app.js') }}"></script>

resources/views/includes/head.blade.php
<title>@yield('title')</title>             
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="description" content="@yield('description')">
<meta name="author" content="Cristian González">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link rel="stylesheet" href="{{ asset('css/app.css') }}">

resources/views/includes/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light mb-4 navbar-front">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item nav-item-front active">
          <a class="nav-link" href="{{route('home')}}">@lang('Inicio')</span></a>
        </li>
        <li class="nav-item nav-item-front dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @lang('Blog')
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"> 
            @foreach($categories as $category)
              <a class="dropdown-item" href="{{route('category', ['id' => $category->slug])}}">{{$category->name}}</a>
            @endforeach
          </div>
        </li>
        <li class="nav-item nav-item-front">
          <a class="nav-link" href="#">@lang('Contacto')</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" method="GET" action="{{ route('articulos.search') }}">
        <input class="form-control @error('q') is-invalid @enderror search-bar mr-sm-2 " name="q" type="search" placeholder="Buscar" aria-label="Buscar" value="{{ old('q') }}">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

resources/views/includes/managerheader.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" style="line-height: 2;">
  <button class="btn btn-primary" id="menu-toggle"><i class="fas fa-bars"></i></button>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url('/') }}">{{ __('Inicio') }}</a>
      </li>
      @guest
        <li class="nav-item">
          <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        @if (Route::has('register'))
          <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
          </li>
        @endif
      @else
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle"></i> {{ Auth::user()->username }}
        </a>         
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          {{-- <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a> --}}
          {{-- <div class="dropdown-divider"></div> --}}
          <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
              <i class="fas fa-sign-out-alt"></i> {{ __('Cerrar sesión') }}
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </div>
      </li>
      @endguest
    </ul>
  </div>
</nav>

resources/views/includes/managersidebar.blade.php
<!-- Sidebar -->
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">
    @lang('Admin Panel')
  </div>
  <ul class="list-group list-group-flush">
    <li class="{{Auth::user()->role_id != 1 ? "d-none" : "" }}">
      <a href="#collapseConfig" class="list-group-item list-group-item-action bg-light" data-toggle="collapse">
        <i class="fas fa-cog mr-1"></i> @lang('Configuración') <i class="fas fa-caret-down float-right"></i>
      </a>
    </li>
    {{-- Collapse from configuration --}}
    <ul class="list-group collapse" id="collapseConfig"> 
      <li>
        <a href="{{ route('configuracion.header') }}" class="list-group-item list-group-item-action bg-light-inside">
          <i class="far fa-circle ml-2 mr-1"></i> @lang('Cabecera')
        </a>
      </li>
    </ul>
    {{-- End collapse from configuration --}}
    <li class="{{Auth::user()->role_id != 1 ? "d-none" : "" }}">
      <a href="{{ route('usuarios.index') }}" class="list-group-item list-group-item-action bg-light">
        <i class="fas fa-users mr-1"></i> @lang('Usuarios')
      </a>
    </li>
    <li class="{{Auth::user()->role_id != 1 ? "d-none" : "" }}">
      <a href="{{ route('roles.index') }}" class="list-group-item list-group-item-action bg-light">
        <i class="fas fa-user-tag mr-1"></i> @lang('Roles')
      </a>
    </li>
    <li class="{{Auth::user()->role_id != 1 ? "d-none" : "" }}">
      <a href="{{ route('redes.index') }}" class="list-group-item list-group-item-action bg-light">
        <i class="fas fa-hashtag mr-1"></i> @lang('Redes sociales')
      </a>
    </li>
    <li>
      <a href="#collapseArticle" class="list-group-item list-group-item-action bg-light" data-toggle="collapse">
        <i class="far fa-newspaper mr-1"></i> @lang('Artículos') <i class="fas fa-caret-down float-right"></i>
      </a>
    </li>
    {{-- Collapse from posts --}}
    <ul class="list-group collapse {{isset($articleCollapse) ? "show" : "" }}" id="collapseArticle"> 
      <li>
        <a href="{{ route('articulos.index') }}" class="list-group-item list-group-item-action bg-light-inside {{isset($articleCollapse) && $articleCollapse == "articleAll" ? "active" : "" }}">
          <i class="far fa-circle ml-2 mr-1"></i> @lang('Ver todos')
        </a>
      </li>
      <li>
        <a href="{{ route('articulos.showFavorites') }}" class="list-group-item list-group-item-action bg-light-inside {{isset($articleCollapse) && $articleCollapse == "articleFavoriteAll" ? "active" : "" }}">
          <i class="far fa-circle ml-2 mr-1"></i> @lang('Ver favoritos')
        </a>
      </li>
    </ul>
    {{-- End collapse from posts --}}
    <li class="{{Auth::user()->role_id != 1 && Auth::user()->role_id != 2 ? "d-none" : "" }}">
      <a href="{{ route('categorias.index') }}" class="list-group-item list-group-item-action bg-light">
        <i class="fas fa-layer-group mr-1"></i> @lang('Categorías')
      </a>
    </li>
  </ul>
</div>
<!-- /#sidebar-wrapper -->