routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/manager', function () {
    return redirect()->route('login');
});

Route::resource('/comentarios', 'CommentController')->only([
    'store'
]);

Route::group(['prefix' => 'manager', 'middleware' => 'auth'], function()
{
	Route::get('/articulos/favoritos', 'PostController@showFavorites')->name('articulos.showFavorites');

	Route::resources([
	    '/articulos' => 'PostController',
	    '/categorias' => 'CategoryController',
	    '/usuarios' => 'UserController',
	    '/redes' => 'SocialController'
	]);

	Route::post('/articulos/{articulo}/quitar', 'PostController@quit')->name('articulos.quit');

	Route::post('/categorias/{articulo}/{categoria}/quitar', 'CategoryController@quit')->name('categorias.quit');

	Route::resource('/roles', 'RoleController')->only([
	    'index', 'show'
	]);

	Route::get('/configuracion/cabecera', 'ConfigController@header')->name('configuracion.header');
});

Route::group(['middleware' => 'shareData'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/categoria/{slug}', 'HomeController@showPostByCategory')->name('category');
	Route::get('/autor/{username}', 'HomeController@showPostByUser')->name('autor');
	Route::get('/buscar', 'HomeController@search')->name('articulos.search');
	Route::get('/{slug}', 'HomeController@showPostBySlug')->name('post');
});

resources/views/pages/autor.blade.php
@extends('layouts.default')
@section('title', 'Home title')
@section('description', 'This is the child meta description')

@section('topContent')
	@include('elements.breadcrumbs', ['actualPageName' => $user->username])
@endsection
@section('content')	
	<div class="row">
		<div class="col-12">
			<div class="separator"><h1>@lang('Autor'): {{$user->username}}</h1></div>
		</div>
	</div>
	<div class="row">
		@include('elements.posts', ['posts' => $userPosts, 'show' => 'col-sm-6', 'images' => 'card-custom-img-slide-2', 'body' => true, 'comments' => true, 'separator' => true])
	</div>
	<div class="row mt-4">
		<div class="col-12">
			{{ $userPosts->links() }}
		</div>
	</div>
@endsection

resources/views/pages/category.blade.php
@extends('layouts.default')
@section('title', $category->metaTitle)
@section('description', $category->metaDescription)

@section('topContent')
	@include('elements.breadcrumbs', ['actualPageName' => $category->name])
@endsection
@section('content')	
	<div class="row">
		<div class="col-12">
			<div class="separator"><h1>@lang('Categoría'): {{$category->name}}</h1></div>
		</div>
	</div>
	<div class="row">
		@include('elements.posts', ['posts' => $categoryPosts, 'show' => 'col-sm-6', 'images' => 'card-custom-img-slide-2', 'body' => true, 'comments' => true, 'separator' => true])
	</div>
	<div class="row mt-4">
		<div class="col-12">
			{{ $categoryPosts->links() }}
		</div>
	</div>
@endsection

resources/views/pages/home.blade.php
@extends('layouts.default')
@section('title', 'Home title')
@section('description', 'This is the child meta description')

@section('topContent')
	@if($favoritePosts->count() > 0)<!-- AUTHORS PICK -->
		<div class="row">
			<div class="col-8 col-md-10">
				<div class="separator"><h2>@lang('Favoritos del autor')</h2></div>
			</div>
			<div class="col-4 col-md-2 text-right align-text-top">
				<span class="owl-custom-nav" id="customNav"></span>
			</div>
		</div>
		<div class="row mb-5">
			<div class="owl-carousel owl-theme" id="owl-carousel-home">
				@include('elements.posts', ['posts' => $favoritePosts, 'show' => '', 'images' => 'card-custom-img-slide-4', 'body' => false, 'comments' => false, 'separator' => false])
			</div>
		</div>
	@endif<!-- END AUTHORS PICK -->
@endsection
@section('content')
	<!-- LATEST POST -->
	<div class="row">
		<div class="col-12">
			<div class="separator"><h2>@lang('Últimos artículos')</h2></div>
		</div>			
	</div>
	@foreach($posts as $post)
		<div class="row mb-4">
			<a class="col-12 col-md-6 custom-card" href="{{route('post', ['id' => $post->slug])}}">
				<div class="wrap">
					<img class="card-custom-img-post" src="{{ asset('storage/images/'.$post->postImage) }}" alt="alt image">
					<div class="middle">
						<button type="button" class="btn btn-lg btn-outline-light">@lang('Leer más')</button>
					</div>
				</div>
			</a>
			<div class="col-12 col-md-6 mt-3 mt-md-0">
				<div class="pull-left"> 
					@foreach ($post->categories as $category)
						<span class="card-custom-title">{{$loop->first ? '' : ', '}}</span>
						<a href="{{route('category', ['id' => $category->slug])}}" class="card-custom-title no-decoration-link">{{$category->name}}</a>	
					@endforeach
				</div>
				<a href="{{route('post', ['id' => $post->slug])}}" class="no-decoration-link subtitle-post-link gray-hover">
					<h2 class="card-custom-subtitle gray-hover-post">{{$post->title}}</h2>
				</a>
				<div class="card-custom-text-post">{{ str_limit(strip_tags($post->body), 200) }}</div>
				<p class="card-custom-text mt-auto">
					<p><a href="{{route('autor', ['id' => $post->user->username])}}" class="no-decoration-link gray-hover">{{$post->user->username}}</a>, <i class="far fa-clock"></i> {{ $post->created_at->diffForHumans() }} <a class="no-decoration-link gray-hover" href="{{route('post', ['id' => $post->slug]).'#comments'}}"><i class="far fa-comment ml-4"></i> {{$post->comments->count()}}</a></p>
				</p>
			</div>
		</div>
	@endforeach
	
	<div class="row mb-5 mb-lg-0">
		<div class="col-12">
			{{ $posts->links() }}
		</div>
	</div>
	<!-- END LATEST POST -->
@endsection

resources/views/pages/post.blade.php
@extends('layouts.default')
@section('title', $post->metaTitle)
@section('description', $post->metaDescription)

@section('topContent')
	@include('elements.breadcrumbs', ['actualPageName' => $post->title])
@endsection
@section('content')
	<div class="row">
		<div class="col-12">
			<img class="post-image" src="{{ asset('storage/images/'.$post->postImage) }}">
		</div>
		<div class="col-12">
			<p class="mt-3"> 
				@foreach ($post->categories as $category)
					<span class="card-custom-title">{{$loop->first ? '' : ', '}}</span>
					<a href="{{route('category', ['id' => $category->id])}}" class="card-custom-title no-decoration-link">{{$category->name}}</a>	
				@endforeach
	        </p>
		</div>
		<div class="col-12">
			<h1 class="title-post">{{$post->title}}</h1>
			<p class="card-custom-text"><i class="far fa-clock"></i> <a href="{{route('autor', ['id' => $post->user->id])}}" class="no-decoration-link gray-hover">{{$post->user->username}}</a>, {{ $post->created_at->diffForHumans() }}</p>
		</div>

		<div class="col-12 mb-5">
			<p>{!! $post->body !!}</p>
		</div>

		<div class="col-12 mt-5"><!-- Carousel articulos relacionados -->			
			<div class="row">
				<div class="col-8 col-md-10">
					<div class="separator"><h3 class="custom-h2">@lang('Artículos relacionados')</h3></div>
				</div>
				<div class="col-4 col-md-2 text-right align-text-top">
					<span class="owl-custom-nav" id="customNav"></span>
				</div>
			</div>

			<div class="row">
				<div class="owl-carousel owl-theme" id="owl-carousel-post">
					@include('elements.posts', ['posts' => $relatedPosts, 'show' => '', 'images' => 'card-custom-img-slide', 'body' => false, 'comments' => false, 'separator' => false])
				</div>
			</div>
		</div><!-- END Carousel articulos relacionados -->
	</div>
	<div class="row mt-5" id="comments">
		<div class="col-12">
			<div class="separator"><h3 class="custom-h2">{{$post->comments->count()}} @choice('messages.comentario', $post->comments->count())</h3></div>
		</div>
		@foreach($post->comments as $comment)
			<div class="col-12 {{$comment->author ? "alert alert-secondary" : "" }}">
				<div class="row">	
					<div class="col-3 col-md-2 text-center">
						<img src="{{$comment->author ? asset('images/logo.png') : asset('images/default_avatar.jpg') }}" class="img-round" alt="User avatar">
					</div>
					<div class="col-9 col-md-10">
						<div class="row">
							<div class="col-12">
								<p class="custom-h3 mb-1">{{$comment->name}}</p>
								<p class="mb-0">{{$comment->body}}</p>
								<p class="card-custom-text"><i class="far fa-clock"></i> {{ $comment->created_at->diffForHumans() }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			@if($post->comments->count() > 1 && !$loop->last)
				<div class="col-12">
					<hr>
				</div>
			@endif
		@endforeach
	</div>
	<div class="row comment-box my-5 mx-1 mx-md-1" id="commentBox">
		<div class="col-12 mb-3">
			<h4 class="custom-h3">@lang('Dejar un comentario')</h4>
		</div>
		<div class="col-12">
			<form action="{{ route('comentarios.store') }}" method="POST">
				@csrf
				<div class="form-row">
					<div class="form-group col-12">
						<input type="hidden" name="post_id" id="post_id" value="{{$post->id}}">
						<label for="inputComment4" class="card-custom-text font-weight-bold">@lang('Comentario') *</label>
                        <textarea class="form-control @error('body') is-invalid @enderror" name="body" rows="5">{{ old('body') }}</textarea>
                        @error('body')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                         @enderror
                    </div>    
			  	</div>
			  	<div class="form-row">
					<div class="form-group col-12 col-md-4">
						<label for="inputName4" class="card-custom-text font-weight-bold">@lang('Nombre') *</label>
						<input type="text" {{ old('name', Auth::check() ? 'readonly' : '') }} class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', Auth::check() ? Auth::user()->username : '') }}">
						@error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                         @enderror
					</div>
					<div class="form-group col-12 col-md-4">
						<label for="inputEmail4" class="card-custom-text font-weight-bold">@lang('Email')</label>
						<input type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}">
						@error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                         @enderror
					</div>
					<div class="form-group col-12 col-md-4">
						<label for="inputWebl4" class="card-custom-text font-weight-bold">@lang('Web')</label>
						<input type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website') }}">
						@error('website')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                         @enderror
					</div>
			  	</div>
			  	<div class="form-row mt-3 flex-column-reverse flex-md-row">
			  		<div class="form-group col-12 col-md-4">
			  			<button type="submit" class="btn btn-dark">@lang('Comentar')</button>
			  		</div>
			  		<div class="form-group col-12 col-md-8 text-md-right">
			  			<p>@lang('Los campos obligatorios están marcados') *</p>
			  		</div>
			  	</div>
			</form>
		</div>
	</div>
@endsection

resources/views/pages/search.blade.php
@extends('layouts.default')
@section('title', 'Resultados de la búsqueda')
@section('description', 'Buscador')

@section('topContent')
	@include('elements.breadcrumbs', ['actualPageName' => "Resultados de búsqueda"])
@endsection
@section('content')	
	<div class="row">
		<div class="col-12">
			<div class="separator"><h1>@lang('Resultados de búsqueda'): {{$inputSearch}}</h1></div>
		</div>
	</div>
	<div class="row">
		@if(count($posts) > 0)
			@include('elements.posts', ['posts' => $posts, 'show' => 'col-sm-6', 'images' => 'card-custom-img-slide-2', 'body' => true, 'comments' => true, 'separator' => true])
		@else
			<div class="col-12">
				<p>@lang('No se han encontrado resultados')</p>
			</div>
		@endif
		
	</div>
	@if(count($posts) > 0)
		<div class="row mt-4">
			<div class="col-12">
				{{ $posts->links() }}
			</div>
		</div>
	@endif
@endsection