routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/manager', function () {
    return redirect()->route('login');
});

Route::resource('/comentarios', 'CommentController')->only([
    'store'
]);

Route::group(['prefix' => 'manager', 'middleware' => 'auth'], function()
{
	Route::get('/articulos/favoritos', 'PostController@showFavorites')->name('articulos.showFavorites');

	Route::resources([
	    '/articulos' => 'PostController',
	    '/categorias' => 'CategoryController',
	    '/usuarios' => 'UserController',
	    '/redes' => 'SocialController'
	]);

	Route::post('/articulos/{articulo}/quitar', 'PostController@quit')->name('articulos.quit');

	Route::post('/categorias/{articulo}/{categoria}/quitar', 'CategoryController@quit')->name('categorias.quit');

	Route::resource('/roles', 'RoleController')->only([
	    'index', 'show'
	]);

	Route::get('/configuracion/cabecera', 'ConfigController@header')->name('configuracion.header');
});

Route::group(['middleware' => 'shareData'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/categoria/{slug}', 'HomeController@showPostByCategory')->name('category');
	Route::get('/autor/{username}', 'HomeController@showPostByUser')->name('autor');
	Route::get('/buscar', 'HomeController@search')->name('articulos.search');
	Route::get('/{slug}', 'HomeController@showPostBySlug')->name('post');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $fillable = [
        'title', 'body', 'slug', 'metaTitle', 'metaDescription', 'user_id', 'postImage', 'visible', 'favorite'
    ];	

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'post_categories')->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\{PostStoreRequest, PostUpdateRequest, PostUpdateFavoriteRequest};
use App\Post;
use App\Traits\ListCategoriesTrait;
use File;

class PostController extends Controller
{
    use ListCategoriesTrait;

    public function index()
	{
    	$posts = Post::latest()->get();
    	return view('manager.posts.all', ['posts' => $posts, 'articleCollapse' => 'articleAll']);
	}

    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('manager.posts.show', ['post' => $post, 'articleCollapse' => 'true']); 
    }

    public function showFavorites()
    {
        $posts = Post::all()->where('favorite', 1);
        return view('manager.posts.allFavorites', ['posts' => $posts, 'articleCollapse' => 'articleFavoriteAll']);
    }

	public function create()
	{
        $categories = $this->getAllCategories();
    	return view('manager.posts.create', compact('categories')); 
	}

	public function store(PostStoreRequest $request)
	{
        $validated = $request->validated();

        //El colaborador no puede publicar sus articulos
        if (auth()->user()->role_id == 4) {
            $validated['visible'] = 0;
            $validated['favorite'] = 0;
        }

        if($request->hasFile('postImage')) {
            $path = $request->file('postImage')->store('public/images');
            $validated['postImage'] = str_replace('public/images/', '', $path);
        }

    	$post = auth()->user()->posts()->create($validated);
        $post->categories()->attach($request->category);
    	return redirect()->route('articulos.index');
	}

	public function edit($id)
    {
        $categories = $this->getAllCategories();
        $post = Post::findOrFail($id);

        //El colaborador no puede editar articulos que no sean suyos
        //El autor no puede editar articulos que no sean suyos
        if (auth()->user()->role_id == 4 && $post->user->id != auth()->user()->id || auth()->user()->role_id == 3 && $post->user->id != auth()->user()->id) {
            return redirect()->route('articulos.index');
        }

        return view('manager.posts.edit',  ['post' => $post, 'categories' => $categories, 'articleCollapse' => 'true']); 
    }

	public function update(PostUpdateRequest $request, $id)
    {
        $validated = $request->validated();
        $post = Post::findOrFail($id);

        //El colaborador no puede editar articulos que no sean suyos 
        if (auth()->user()->role_id == 4 && $post->user->id != auth()->user()->id || auth()->user()->role_id == 3 && $post->user->id != auth()->user()->id) {
            return redirect()->route('articulos.index');
        }

        //El colaborador no puede publicar sus articulos
        if (auth()->user()->role_id == 4) {
            $validated['visible'] = 0;
            $validated['favorite'] = 0;
        }

        if($request->hasFile('postImage')) {
            $path = $request->file('postImage')->store('public/images');
            $validated['postImage'] = str_replace('public/images/', '', $path);
        }

        $post->update($validated);
        $post->categories()->sync($request->category); 
        return redirect()->route('articulos.index');
    }

	public function destroy($id)
    {
        $post = Post::findOrFail($id);

        //El colaborador no puede borrar articulos
        //El autor solo puede borrar sus articulos
        if (auth()->user()->role_id == 4 || auth()->user()->role_id == 3 && $post->user->id != auth()->user()->id) {
            return redirect()->route('articulos.index');
        }

        $post->delete();
    	return redirect()->route('articulos.index');
    }

    public function quit(PostUpdateFavoriteRequest $request, $id)
    {
        $validated = $request->validated();
        $post = Post::findOrFail($id);

        //El colaborador no puede quitar articulos favoritos
        if (auth()->user()->role_id == 4) {
            return redirect()->route('articulos.index');
        }

        $post->update($validated);
        return redirect()->route('articulos.showFavorites');
    }
}

resources/views/manager/posts/all.blade.php
@extends('layouts.manager')
@section('title', 'Listado de artículos')
@section('description', 'Listado de artículos')
@section('content')
	@include('elements.modalConfirmDelete', ['id' => 'delete', 'title' => 'Eliminar artículo', 'message' => 'Esta acción no se puede deshacer', 'route' => 'articulos.destroy'])

	<div class="row">
		<div class="col-12">
			<div class="backend-card">
	            <div class="card-header">
					<h1><i class="far fa-folder-open"></i> Artículos</h1>
	            </div>
	            <div class="card-body">
	                <div class="row">
	                    <div class="col-12">
							<a role="button" href="{{ route('articulos.create') }}" class="btn btn-success pull-left"><i class="fas fa-plus"></i> Nuevo</a>
	                    </div>
	                </div>
	                <div class="row">
	                    <div class="col-12">
							<table id="dataTable" class="table table-hover table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
								<thead class="thead-dark"> 
									<tr> 
										<th>Miniatura</th>
										<th class="datetable-title">Titulo</th>
										<th>Visible</th>
										<th>Autor</th> 
										<th>Categorias</th>
										<th>Creado</th> 
										<th>Actualizado</th>
										<th>Acciones</th>
									</tr>
								</thead> 
								<tbody> 
									@foreach ($posts as $post)
										<tr> 
											<td class="text-center"><img class="img-thumbnail backend-image-xs" src="{{ asset('storage/images/'.$post->postImage) }}"></td>
											<td class="text-wrap">{{ $post->title }}</td>
											<td class="text-center">
												<span class="d-none">{{$post->visible}}</span>
												@if($post->visible)
													<i class="fas fa-check text-success"></i>
												@else
													<i class="fas fa-times text-danger"></i>
												@endif
											</td>
											<td><a href="{{route('usuarios.show', $post->user->id)}}">{{$post->user->username}}</a></td>
											<td>
												@if($post->categories->count() > 0)
													@foreach ($post->categories as $category)
														{{$loop->first ? '' : ', '}}
														<a href="{{route('categorias.show', ['id' => $category->id])}}">{{$category->name}}</a> 	
													@endforeach
												@else
													Sin categoría
												@endif
												
											</td>
											<td>{{$post->created_at}}</td>
											<td>{{$post->updated_at}}</td>
											<td>
												<div class="btn-group d-inline d-xl-none" role="group">
													<a href="{{route('articulos.show', $post->id)}}" role="button" class="btn btn-success"><i class="far fa-eye"></i></a>
												 	
												 	@if($post->user->id == Auth::user()->id || Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
												 		<a href="{{route('articulos.edit', $post->id)}}" role="button" class="btn btn-primary"><i class="far fa-edit"></i></a>
												 	@endif

												 	@if($post->user->id == Auth::user()->id && Auth::user()->role_id != 4 || Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
												 		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{$post->id}}"><i class="far fa-trash-alt"></i></button>
												 	@endif
												</div>

												<div class="d-none d-xl-block">
													<a href="{{route('articulos.show', $post->id)}}" role="button" class="btn btn-outline-success"><i class="far fa-eye"></i> Ver</a>

													@if($post->user->id == Auth::user()->id || Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
				      									<a href="{{route('articulos.edit', $post->id)}}" role="button" class="btn btn-outline-primary"><i class="far fa-edit"></i> Editar</a>
				      								@endif

				      								@if($post->user->id == Auth::user()->id && Auth::user()->role_id != 4 || Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
				      									<button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{$post->id}}"><i class="far fa-trash-alt"></i> Eliminar</button>
				      								@endif
													
												</div>
											</td>
										</tr>
									@endforeach
								</tbody> 
							</table>
	                    </div>
	                </div>
	            </div>
	        </div>
    	</div>
	</div>
@endsection

resources/views/manager/posts/allFavorites.blade.php
@extends('layouts.manager')
@section('title', 'Listado de artículos favoritos')
@section('description', 'Listado de artículos favoritos')

@section('content')
    @include('manager.posts.modalConfirmFavoriteRemove')

    <div class="row">
        <div class="col-12">
            <div class="backend-card">
                <div class="card-header">
                    <h1><i class="far fa-folder-open"></i> Artículos favoritos</h1>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-info" role="alert">
                                Los artículos de esta lista se mostrarán en la sección "Favoritos del autor" de la página inicial, eliminar todos los favoritos ocultará la sección.
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <table id="dataTable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead class="thead-dark"> 
                                    <tr> 
                                        <th>Miniatura</th>
                                        <th class="datetable-title">Titulo</th>
                                        <th>Visible</th>
                                        <th>Autor</th> 
                                        <th>Categorias</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead> 
                                <tbody> 
                                    @foreach ($posts as $post)
                                        <tr class="alert-success text-body"> 
                                            <td class="text-center"><img class="img-thumbnail backend-image-xs" src="{{ asset('storage/images/'.$post->postImage) }}"></td>
                                            <td class="text-wrap">{{$post->title}}</td>
                                            <td class="text-center">
                                                <span class="d-none">{{$post->visible}}</span>
                                                @if($post->visible)
                                                    <i class="fas fa-check text-success"></i>
                                                @else
                                                    <i class="fas fa-times text-danger"></i>
                                                @endif
                                            </td>
                                            <td><a href="{{route('usuarios.show', $post->user->id)}}">{{$post->user->username}}</a></td>
                                            <td>
                                                @if($post->categories->count() > 0)
                                                    @foreach ($post->categories as $category)
                                                        {{$loop->first ? '' : ', '}}
                                                        <a href="{{route('categorias.show', ['id' => $category->id])}}">{{$category->name}}</a>     
                                                    @endforeach
                                                @else
                                                    Sin categoría
                                                @endif
                                            </td>
                                            <td>
                                                <div class="btn-group d-inline d-xl-none" role="group">
                                                    <a href="{{route('articulos.show', $post->id)}}" role="button" class="btn btn-success"><i class="far fa-eye"></i></a>
                                                    
                                                    @if(Auth::user()->role_id == 1)
                                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeFavoriteArticleModal" data-id="{{$post->id}}"><i class="fas fa-minus-circle"></i></button>
                                                    @endif

                                                </div>

                                                <div class="d-none d-xl-block">
                                                    <a href="{{route('articulos.show', $post->id)}}" role="button" class="btn btn-success"><i class="far fa-eye"></i> Ver</a>
                                                   
                                                    @if(Auth::user()->role_id == 1)
                                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeFavoriteArticleModal" data-id="{{$post->id}}"><i class="fas fa-minus-circle"></i> Quitar</button>
                                                    @endif
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody> 
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/posts/create.blade.php
@extends('layouts.manager')
@section('title', 'Crear nuevo artículo')
@section('description', 'Creación de nuevos artículos desde el backend')

@section('content')
    <form class="form-horizontal col-12" action="{{ route('articulos.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row mt-3">
            <div class=" col-12 text-right">
                <a href="{{route('articulos.index')}}" role="button" class="btn btn-success"><i class="fas fa-arrow-left"></i> Volver</a>
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>
        </div>

        <div class="row flex-column-reverse flex-xl-row">
            <div class="col-xl-8 col-12">
                <div class="backend-card">
                    <div class="card-header">
                        <div class="backend-card-title">Crear nuevo artículo</div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12">
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Título" value="{{ old('title') }}">
                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>

                            <div class="form-group col-12">
                                <textarea id="summernote" class="form-control @error('body') is-invalid @enderror" name="body">{{ old('body') }}</textarea>
                                @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                 @enderror
                            </div>    
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-12">   
                <div class="row">
                    <div class="col-12">    
                        <div class="backend-card">
                            <div class="card-header">
                                <div class="backend-card-title">Apartado SEO</div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-12">                       
                                        <input type="text" class="form-control form-control-sm  @error('metaTitle') is-invalid @enderror" name="metaTitle" placeholder="Meta título" value="{{ old('metaTitle') }}">
                                        @error('metaTitle')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                        @enderror
                                    </div>

                                    <div class="form-group col-12">
                                        <input type="text" class="form-control form-control-sm @error('slug') is-invalid @enderror" name="slug" placeholder="URL" value="{{ old('slug') }}">
                                        @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>

                                    <div class="form-group col-12">
                                        <textarea class="form-control @error('metaDescription') is-invalid @enderror" name="metaDescription" placeholder="Meta descripción" rows="2">{{ old('metaDescription') }}</textarea>
                                        @error('metaDescription')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">    
                        <div class="backend-card">
                            <div class="card-header">
                                <div class="backend-card-title">Miniatura</div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-12">
                                        <div class="form-group">
                                            <input type="file" class="form-control-file @error('postImage') is-invalid @enderror" name="postImage">
                                        
                                            @error('postImage')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">    
                        <div class="backend-card">
                            <div class="card-header">
                                <div class="backend-card-title">Opciones</div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-12">                            
                                        <div class="custom-control custom-switch">
                                            <input type="hidden" name="visible" value="0">
                                            <input type="checkbox" class="custom-control-input @error('visible') is-invalid @enderror" name="visible" id="visible" value="1" @if(old('visible')) checked @endif>
                                            <label class="custom-control-label" for="visible">Visible</label>
                                            @error('visible')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group col-12">                            
                                        <div class="custom-control custom-switch">
                                            <input type="hidden" name="favorite" value="0">
                                            <input type="checkbox" class="custom-control-input @error('favorite') is-invalid @enderror" name="favorite" id="favorite" value="1" @if(old('favorite')) checked @endif>
                                            <label class="custom-control-label" for="favorite">Favorito</label>
                                            @error('favorite')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">    
                        <div class="backend-card">
                            <div class="card-header">
                                <div class="backend-card-title">Categoría</div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-12">
                                        <select class="form-control selectpicker" multiple name="category[]" title="Categoría">
                                            @foreach ($categories as $category)
                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/manager/posts/show.blade.php
@extends('layouts.manager')
@section('title', 'Ver artículo')
@section('description', 'Ver un artículo desde el backend')

@section('content')
    <div class="row mt-3">
        <div class=" col-12 text-right">
            <a href="{{ url()->previous() }}" role="button" class="btn btn-success"><i class="fas fa-arrow-left"></i> Volver</a>
            @if($post->user->id == Auth::user()->id || Auth::user()->role_id == 1 || Auth::user()->role_id == 2)
                <a href="{{route('articulos.edit', $post->id)}}" role="button" class="btn btn-primary"><i class="far fa-edit"></i> Editar</a>
            @endif
        </div>
    </div>
    <div class="row flex-column-reverse flex-xl-row">
        <div class="col-xl-8 col-12">
            <div class="backend-card">
                <div class="card-header">
                    <div class="backend-card-title">Vista previa del artículo</div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h1>{{$post->title}}</h1>
                        </div>

                        <div class="col-12">
                            <p>{!! $post->body !!}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-12">
            <div class="row">
                <div class="col-12">
                    <div class="backend-card">
                        <div class="card-header">
                            <div class="backend-card-title">Información general</div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <label class="font-weight-bold">Autor: </label><a href="{{route('usuarios.show', $post->user->id)}}"> {{$post->user->username}}</a>
                                </div>
                                <div class="col-12">
                                    <label class="font-weight-bold">Categorías: </label>
                                    <p class="d-inline"> 
                                        @if($post->categories->count() > 0)
                                            @foreach ($post->categories as $category)
                                                {{$loop->first ? '' : ', '}}
                                                <a href="{{route('categorias.show', ['id' => $category->id])}}">{{$category->name}}</a>     
                                            @endforeach
                                        @else
                                                Sin categoría
                                        @endif
                                    </p>
                                </div>

                                <div class="col-12">
                                    <p class="font-weight-bold d-inline">Visible: </p>
                                    @if($post->visible)
                                        <i class="fas fa-check text-success"></i>
                                    @else
                                        <i class="fas fa-times text-danger"></i>
                                    @endif
                                </div>

                                <div class="col-12 text-center">
                                    <label class="font-weight-bold d-block">Miniatura</label>
                                    <img class="img-thumbnail backend-image" src="{{ asset('storage/images/'.$post->postImage) }}">
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-12">
                    <div class="backend-card">
                        <div class="card-header">
                            <div class="backend-card-title">Apartado SEO</div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <label class="font-weight-bold">Link: </label><a href="{{$post->slug}}"> {{route('home')}}/{{$post->slug}}</a>
                                </div>

                                <div class="col-12">
                                     <label class="font-weight-bold">Título de la página: </label><p class="d-inline"> {{$post->metaTitle}}</p>
                                </div>

                                <div class="col-12">
                                    <label class="font-weight-bold">Descripción de la página: </label><p class="d-inline"> {{$post->metaDescription}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection